Rename SDL_LIBRARY to SDL_LIBRARIES
This is so that you can actually be able to compile BetterSpades and not get 'undefined reference to SDL_blahblahblah'